const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{RQCatchBug: 0},
	{Feature: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{RQCatchEngineer: 0},
	{RQCatchScoreboard: 0},
	{GoldenFeature: 0},
	{RQCatchBackground: 0},
	{RQCatchBoundry: 0},
	{RQCatcherScoreboardBackground: 0},
	{RQCatchEndgameText: 0},
	{RQCatherRetry: 0},
	{RQCatchContButton: 0},
	{Platform: 0},
	{Payhawk: 0},
	{Solid: 0},
	{PayHawkFloor: 0},
	{DestroyOutsideLayout: 0},
	{GoodItem: 0},
	{LowerBarrier: 0},
	{PayhawkBadItem: 0},
	{PayhawkScoreboard: 0},
	{PayhawkTiledBackground: 0},
	{PayhawkSpikeBall: 0},
	{PayhawkEndgameText: 0},
	{PayhawkTryAgain: 0},
	{PayhawkCont: 0},
	{RQCatchSpawnFrequency: 0},
	{GravityStrength: 0},
	{Features: 0},
	{RQCatchClock: 0},
	{RQCatchGameOver: 0},
	{Bugs: 0},
	{PayhawkGameOver: 0},
	{PayhawkScore: 0},
	{WinningScore: 0},
	{PayhawkClock: 0}
];

self.InstanceType = {
	RQCatchBug: class extends self.ISpriteInstance {},
	Feature: class extends self.ISpriteInstance {},
	RQCatchEngineer: class extends self.ISpriteInstance {},
	RQCatchScoreboard: class extends self.ITextInstance {},
	GoldenFeature: class extends self.ISpriteInstance {},
	RQCatchBackground: class extends self.ITiledBackgroundInstance {},
	RQCatchBoundry: class extends self.ISpriteInstance {},
	RQCatcherScoreboardBackground: class extends self.ISpriteInstance {},
	RQCatchEndgameText: class extends self.ITextInstance {},
	RQCatherRetry: class extends self.IButtonInstance {},
	RQCatchContButton: class extends self.IButtonInstance {},
	Payhawk: class extends self.ISpriteInstance {},
	PayHawkFloor: class extends self.ISpriteInstance {},
	GoodItem: class extends self.ISpriteInstance {},
	LowerBarrier: class extends self.ISpriteInstance {},
	PayhawkBadItem: class extends self.ISpriteInstance {},
	PayhawkScoreboard: class extends self.ITextInstance {},
	PayhawkTiledBackground: class extends self.ITiledBackgroundInstance {},
	PayhawkSpikeBall: class extends self.ISpriteInstance {},
	PayhawkEndgameText: class extends self.ITextInstance {},
	PayhawkTryAgain: class extends self.IButtonInstance {},
	PayhawkCont: class extends self.IButtonInstance {}
}