const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{SLA: 0},
	{WorkRemaining: 0},
	{InitalSLA: 0},
	{Occupied: 0},
	{AppsTicket: 0},
	{AppsWorkRate: 0},
	{InfraWorkRate: 0},
	{InfraEngineer: 0},
	{ScoreBoard: 0},
	{InfraTicket: 0},
	{MajorIncident: 0},
	{AppsEngineer: 0},
	{TiledBackground: 0},
	{SrApp: 0},
	{GameOver: 0},
	{DragDrop: 0},
	{Engineers: 0},
	{Tickets: 0},
	{Breeches: 0},
	{Resolves: 0},
	{Clock: 0},
	{TicketSpawnFrequency: 0},
	{TicketSpawnFrequencyRate: 0}
];

self.InstanceType = {
	AppsTicket: class extends self.ISpriteInstance {},
	InfraEngineer: class extends self.ISpriteInstance {},
	ScoreBoard: class extends self.ITextInstance {},
	InfraTicket: class extends self.ISpriteInstance {},
	MajorIncident: class extends self.ISpriteInstance {},
	AppsEngineer: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	SrApp: class extends self.ISpriteInstance {},
	GameOver: class extends self.ITextInstance {},
	Engineers: class extends self.ISpriteInstance {},
	Tickets: class extends self.ISpriteInstance {}
}